version: '3.8'

services:
  client:
    container_name: smart-chess
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/smart-chess-front"
      - "/smart-chess-front/node_modules"
    ports:
      - "3000:3000"